name: ServerCasino
version: 0.5.0-preview
main: dev.server.casino.CasinoPlugin
api-version: '26.2'
softdepend: [Vault, AuthMe, CraftEngine, ServerGames]
commands:
  casino-demo:
    description: 创建或清除实体游乐机
    usage: /casino-demo create <game> [skin-id] 或 remove [game] 或 reload-models
  casino:
    description: 金币游乐场
    usage: /casino [create <game> [skin-id] | bet <game> <1-100> | remove [game] | reload-models]
permissions:
  casino.machine:
    default: op
  casino.use:
    default: true
